In [1]:
import numpy as np

1. Create a 1D array of numbers from 0 to 9.

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3×3 numpy array of all True’s

Didnot know what True's meant a string or boolean so used both 

In [3]:
np.full((3,3),'True')

array([['True', 'True', 'True'],
       ['True', 'True', 'True'],
       ['True', 'True', 'True']], dtype='<U4')

In [4]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Given an array as input, print only odd numbers as output

In [6]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
print(a[a%2!=0])

[1 3 5 7 9]


4. Replace all odd numbers in arr with -2

In [8]:
a[a%2!=0] = -2
print(a)

[ 0 -2  2 -2  4 -2  6 -2  8 -2]


5. How to reshape an array?

Using np.reshape or np.resize .
The difference is np.reshape creates a temporary copy whereas np.resize does it inplace.
Also np.reshape can't reshape into bigger size whereas np.resize can, it appends 0.

6. Convert a 1D array to a 2D array with 2 rows

In [10]:
b = np.array([0,1,2,3])
print(b)
c = b.reshape((2,2))
print(c)

[0 1 2 3]
[[0 1]
 [2 3]]


7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples. 

In [14]:
#advanced indexing
a = np.array([1,2,3,4,5,6,7,8,9])
b = a[(a%2!=0) | (a%4==0)]
print(b)

[1 3 4 5 7 8 9]


In [19]:
#using np.where function
a = np.array([1,2,3,4,5,6,7,8,9])
b = a[np.where((a%2!=0) |(a%4==0))]
print(b)

[1 3 4 5 7 8 9]


8. Given array, check if there are any null values and print them out. 

In [30]:
x = np.array([1,2,np.nan,3,7,8,np.nan])
print(x)
print(np.isnan(x))

[ 1.  2. nan  3.  7.  8. nan]
[False False  True False False False  True]


9. How to replace all missing values with 0 in a numpy array?

In [32]:
mask = np.isnan(x)
x[mask] = 0
print(x)

[1. 2. 0. 3. 7. 8. 0.]


10. How to find the count of each unique number in a NumPy array?

In [39]:
a = np.array([1,2,3,4,1,4,5,6,2,2,2,2])
a,count = np.unique(a,return_counts=True)
print("Unique Elements in array",a)
print("Count of unique elements in array",count)


Unique Elements in array [1 2 3 4 5 6]
Count of unique elements in array [2 5 1 2 1 1]


11. How to convert a numeric to a categorical (text) array?

In [45]:
a = np.array([1,2,3,4,5,6,7,8],dtype=int)
print(a.dtype)
print(a)
b = np.full_like(a,a,dtype=str)
print(b.dtype)
print(b)

int64
[1 2 3 4 5 6 7 8]
<U1
['1' '2' '3' '4' '5' '6' '7' '8']


12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. 

In [57]:
x = np.arange(99,300)
print(x[(x%5==0)|(x%7==0) & (x%35!=0)])

[100 105 110 112 115 119 120 125 126 130 133 135 140 145 147 150 154 155
 160 161 165 168 170 175 180 182 185 189 190 195 196 200 203 205 210 215
 217 220 224 225 230 231 235 238 240 245 250 252 255 259 260 265 266 270
 273 275 280 285 287 290 294 295]


13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

In [50]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
b = a[::-1]
print(b)

[9 8 7 6 5 4 3 2 1 0]
